/*
 *  Copyright (C) 2021 Texas Instruments Incorporated
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *    Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 *    Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the
 *    distribution.
 *
 *    Neither the name of Texas Instruments Incorporated nor the names of
 *    its contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 *  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 *  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 *  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 *  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 *  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 *  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 *  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 *  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/*
 * Auto generated file
 */

#ifndef TI_DRIVERS_CONFIG_H_
#define TI_DRIVERS_CONFIG_H_

#include <stdint.h>
#include <drivers/hw_include/cslr_soc.h>
#include <drivers/hw_include/hw_types.h>
#include "ti_dpl_config.h"

#ifdef __cplusplus
extern "C" {
#endif


/*
 * Common Functions
 */
void System_init(void);
void System_deinit(void);

/*
 * GPIO
 */
#include <drivers/gpio.h>
#include <kernel/dpl/AddrTranslateP.h>

/* GPIO PIN Macros */
#define CONFIG_GPIO_STB_MCAN4_BASE_ADDR (CSL_GPIO3_U_BASE)
#define CONFIG_GPIO_STB_MCAN4_PIN (43)
#define CONFIG_GPIO_STB_MCAN4_DIR (GPIO_DIRECTION_OUTPUT)
#define CONFIG_GPIO_STB_MCAN4_TRIG_TYPE (GPIO_TRIG_TYPE_NONE)
#define CONFIG_GPIO_STB_MCAN3_BASE_ADDR (CSL_GPIO3_U_BASE)
#define CONFIG_GPIO_STB_MCAN3_PIN (45)
#define CONFIG_GPIO_STB_MCAN3_DIR (GPIO_DIRECTION_OUTPUT)
#define CONFIG_GPIO_STB_MCAN3_TRIG_TYPE (GPIO_TRIG_TYPE_NONE)
#define CONFIG_GPIO_STB_MCAN5_BASE_ADDR (CSL_GPIO3_U_BASE)
#define CONFIG_GPIO_STB_MCAN5_PIN (62)
#define CONFIG_GPIO_STB_MCAN5_DIR (GPIO_DIRECTION_OUTPUT)
#define CONFIG_GPIO_STB_MCAN5_TRIG_TYPE (GPIO_TRIG_TYPE_NONE)
#define CONFIG_GPIO_STB_MCAN7_BASE_ADDR (CSL_GPIO3_U_BASE)
#define CONFIG_GPIO_STB_MCAN7_PIN (70)
#define CONFIG_GPIO_STB_MCAN7_DIR (GPIO_DIRECTION_OUTPUT)
#define CONFIG_GPIO_STB_MCAN7_TRIG_TYPE (GPIO_TRIG_TYPE_NONE)
#define CONFIG_GPIO_STB_MCAN2_BASE_ADDR (CSL_GPIO3_U_BASE)
#define CONFIG_GPIO_STB_MCAN2_PIN (130)
#define CONFIG_GPIO_STB_MCAN2_DIR (GPIO_DIRECTION_OUTPUT)
#define CONFIG_GPIO_STB_MCAN2_TRIG_TYPE (GPIO_TRIG_TYPE_NONE)
#define CONFIG_GPIO_STB_MCAN1_BASE_ADDR (CSL_GPIO3_U_BASE)
#define CONFIG_GPIO_STB_MCAN1_PIN (83)
#define CONFIG_GPIO_STB_MCAN1_DIR (GPIO_DIRECTION_OUTPUT)
#define CONFIG_GPIO_STB_MCAN1_TRIG_TYPE (GPIO_TRIG_TYPE_NONE)
#define CONFIG_GPIO_STB_MCAN6_BASE_ADDR (CSL_GPIO3_U_BASE)
#define CONFIG_GPIO_STB_MCAN6_PIN (44)
#define CONFIG_GPIO_STB_MCAN6_DIR (GPIO_DIRECTION_OUTPUT)
#define CONFIG_GPIO_STB_MCAN6_TRIG_TYPE (GPIO_TRIG_TYPE_NONE)
#define CONFIG_GPIO_STB_MCAN0_BASE_ADDR (CSL_GPIO3_U_BASE)
#define CONFIG_GPIO_STB_MCAN0_PIN (84)
#define CONFIG_GPIO_STB_MCAN0_DIR (GPIO_DIRECTION_OUTPUT)
#define CONFIG_GPIO_STB_MCAN0_TRIG_TYPE (GPIO_TRIG_TYPE_NONE)
#define CONFIG_GPIO_NUM_INSTANCES (8U)
/*
 * IPC Notify
 */
#include <drivers/ipc_notify.h>


/*
 * MCAN
 */
#include <drivers/mcan.h>

/* MCAN Instance Macros */
#define CONFIG_MCAN3_BASE_ADDR (CSL_MCAN3_MSG_RAM_U_BASE)
#define CONFIG_MCAN3_INTR  (CSLR_R5FSS1_CORE1_INTR_MCAN3_MCAN_LVL_INT_0)
#define CONFIG_MCAN3_INTR1 (CSLR_R5FSS1_CORE1_INTR_MCAN3_MCAN_LVL_INT_1)
#define CONFIG_MCAN2_BASE_ADDR (CSL_MCAN2_MSG_RAM_U_BASE)
#define CONFIG_MCAN2_INTR  (CSLR_R5FSS1_CORE1_INTR_MCAN2_MCAN_LVL_INT_0)
#define CONFIG_MCAN2_INTR1 (CSLR_R5FSS1_CORE1_INTR_MCAN2_MCAN_LVL_INT_1)
#define CONFIG_MCAN7_BASE_ADDR (CSL_MCAN7_MSG_RAM_U_BASE)
#define CONFIG_MCAN7_INTR  (CSLR_R5FSS1_CORE1_INTR_MCAN7_MCAN_LVL_INT_0)
#define CONFIG_MCAN7_INTR1 (CSLR_R5FSS1_CORE1_INTR_MCAN7_MCAN_LVL_INT_1)
#define CONFIG_MCAN6_BASE_ADDR (CSL_MCAN6_MSG_RAM_U_BASE)
#define CONFIG_MCAN6_INTR  (CSLR_R5FSS1_CORE1_INTR_MCAN6_MCAN_LVL_INT_0)
#define CONFIG_MCAN6_INTR1 (CSLR_R5FSS1_CORE1_INTR_MCAN6_MCAN_LVL_INT_1)
#define CONFIG_MCAN0_BASE_ADDR (CSL_MCAN0_MSG_RAM_U_BASE)
#define CONFIG_MCAN0_INTR  (CSLR_R5FSS1_CORE1_INTR_MCAN0_MCAN_LVL_INT_0)
#define CONFIG_MCAN0_INTR1 (CSLR_R5FSS1_CORE1_INTR_MCAN0_MCAN_LVL_INT_1)
#define CONFIG_MCAN1_BASE_ADDR (CSL_MCAN1_MSG_RAM_U_BASE)
#define CONFIG_MCAN1_INTR  (CSLR_R5FSS1_CORE1_INTR_MCAN1_MCAN_LVL_INT_0)
#define CONFIG_MCAN1_INTR1 (CSLR_R5FSS1_CORE1_INTR_MCAN1_MCAN_LVL_INT_1)
#define CONFIG_MCAN4_BASE_ADDR (CSL_MCAN4_MSG_RAM_U_BASE)
#define CONFIG_MCAN4_INTR  (CSLR_R5FSS1_CORE1_INTR_MCAN4_MCAN_LVL_INT_0)
#define CONFIG_MCAN4_INTR1 (CSLR_R5FSS1_CORE1_INTR_MCAN4_MCAN_LVL_INT_1)
#define CONFIG_MCAN5_BASE_ADDR (CSL_MCAN5_MSG_RAM_U_BASE)
#define CONFIG_MCAN5_INTR  (CSLR_R5FSS1_CORE1_INTR_MCAN5_MCAN_LVL_INT_0)
#define CONFIG_MCAN5_INTR1 (CSLR_R5FSS1_CORE1_INTR_MCAN5_MCAN_LVL_INT_1)
#define CONFIG_MCAN_NUM_INSTANCES (8U)


/*
 * UART
 */
#include <drivers/uart.h>
/* UART Instance Macros */
#define CONFIG_UART5 (0U)
#define CONFIG_UART_NUM_INSTANCES (1U)
#define CONFIG_UART_NUM_DMA_INSTANCES (0U)


#include <drivers/soc.h>
#include <kernel/dpl/CycleCounterP.h>

/*
 * MCU_LBIST
 */
void SDL_lbist_selftest(void);

#ifdef __cplusplus
}
#endif

#endif /* TI_DRIVERS_CONFIG_H_ */
