/**
 * @file can_config.h
 * @brief CAN Configuration for Core 1 (NoRTOS)
 *
 * Configuration from SysConfig - requires ti_drivers_config.h
 *
 * @author CCU Multicore Project
 * @date 2026-03-28
 */

#ifndef CAN_CONFIG_H_
#define CAN_CONFIG_H_

#include <stdint.h>

/* Include SysConfig-generated definitions
 * After running SysConfig with MCAN module configured,
 * ti_drivers_config.h will contain:
 * - CONFIG_MCANx_BASE_ADDR for x=0..7
 * - CONFIG_MCANx_INTR for x=0..7
 * - CONFIG_GPIO_STB_MCANx_BASE_ADDR, PIN, DIR for x=0..7
 */
#include "ti_drivers_config.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Note: MCAN base addresses and GPIO STB definitions are now provided by
 * ti_drivers_config.h (generated by SysConfig from example.syscfg)
 *
 * If compilation fails with "undefined symbol" errors:
 * 1. Open ccu_ti_multi_core_realtime/example.syscfg in SysConfig GUI
 * 2. Verify MCAN module is configured (MCAN0-7 instances)
 * 3. Verify GPIO instances are configured (GPIO_STB_MCAN0-7)
 * 4. Generate code
 * 5. Rebuild project
 */

/* Legacy fallback definitions (will be removed after SysConfig is properly configured) */
#ifndef CONFIG_MCAN0_BASE_ADDR

#define CSL_MCANSS0_BASE_ADDR             0x2700000U
#define CSL_MCAN0_BASE                   (CSL_MCANSS0_BASE_ADDR + 0x0000U)
#define CSL_MCAN1_BASE                   (CSL_MCANSS0_BASE_ADDR + 0x1000U)
#define CSL_MCAN2_BASE                   (CSL_MCANSS0_BASE_ADDR + 0x2000U)
#define CSL_MCAN3_BASE                   (CSL_MCANSS0_BASE_ADDR + 0x3000U)
#define CSL_MCAN4_BASE                   (CSL_MCANSS0_BASE_ADDR + 0x4000U)
#define CSL_MCAN5_BASE                   (CSL_MCANSS0_BASE_ADDR + 0x5000U)
#define CSL_MCAN6_BASE                   (CSL_MCANSS0_BASE_ADDR + 0x6000U)
#define CSL_MCAN7_BASE                   (CSL_MCANSS0_BASE_ADDR + 0x7000U)

#define CONFIG_MCAN0_BASE_ADDR           CSL_MCAN0_BASE
#define CONFIG_MCAN1_BASE_ADDR           CSL_MCAN1_BASE
#define CONFIG_MCAN2_BASE_ADDR           CSL_MCAN2_BASE
#define CONFIG_MCAN3_BASE_ADDR           CSL_MCAN3_BASE
#define CONFIG_MCAN4_BASE_ADDR           CSL_MCAN4_BASE
#define CONFIG_MCAN5_BASE_ADDR           CSL_MCAN5_BASE
#define CONFIG_MCAN6_BASE_ADDR           CSL_MCAN6_BASE
#define CONFIG_MCAN7_BASE_ADDR           CSL_MCAN7_BASE

#warning "Using legacy MCAN base address defines - SysConfig MCAN module not configured!"

#endif /* CONFIG_MCAN0_BASE_ADDR */

#ifdef __cplusplus
}
#endif

#endif /* CAN_CONFIG_H_ */
